### ISSUE TITLE
Unable To View The Processed Document After Pdfminer

### ISSUE THREAD

**Issue by AyeshaSarwar** [axa-group/Parsr#311]
![Capture](https://user-images.githubusercontent.com/51691311/73488695-341d9f00-43cb-11ea-8a56-ff8f102afa5b.PNG)
 I am unable to view my processed document in case of pdfminer.

**Comment by jvalls-axa** [comment]
Hi @AyeshaSarwar a little more information would be very helpful...

Can you please copy & paste the full API console log? 
Can you attach used file?

Thanks

**Comment by AyeshaSarwar** [comment]
![1](https://user-images.githubusercontent.com/51691311/73533744-5520d700-4441-11ea-880f-80bb67e37cfe.PNG)
![2](https://user-images.githubusercontent.com/51691311/73533746-5520d700-4441-11ea-9afe-284343167d87.PNG)

It is not generating pdf, however I have installed pdfminer.six

**Comment by AyeshaSarwar** [comment]
Does the file pdf2txt.py need to be accessible from anywhere in the computer? I am not sure about this. Since, It cant be accessed.

**Comment by AyeshaSarwar** [comment]
As it is a filename

**Comment by marianorodriguez** [comment]
Hello @AyeshaSarwar !
Just to make sure you have every required library installed, please attach a capture of the table in `http://localhost:3001/api/check-installation` (with the API running)

**Comment by jvalls-axa** [comment]
Yes, pdf2txt.py should be in PATH

Try this --> http://localhost:3001/api/v1/check-installation

If pdf2txt.py displayed in red is because is not installed or not in PATH

**Comment by AyeshaSarwar** [comment]
![3](https://user-images.githubusercontent.com/51691311/73534358-be551a00-4442-11ea-83a1-b3d18ea2bbd1.PNG)

**Comment by AyeshaSarwar** [comment]
pdf2txt.py is in path

**Comment by AyeshaSarwar** [comment]
![4](https://user-images.githubusercontent.com/51691311/73534563-3c192580-4443-11ea-943e-bdd5663fb644.PNG)

**Comment by jvalls-axa** [comment]
Hi @AyeshaSarwar 

Seems that pdf2txt is failing but there is no error information in console.

Could you please:
1) Edit https://github.com/axa-group/Parsr/blob/e1d11ac22859f5b238eddfe19de9f5d138e57b28/server/src/utils.ts#L75

2) change it for --> ` logger.info(`executing command: ${command} ${args.join(' ')}`);`
3) Run again and copy from terminal the pdf2txt command.
4) Execute it in other terminal window just to see if there is more error information displayed

**Comment by AyeshaSarwar** [comment]
pdf2txt.py -c utf-8 -t xml -o C:\Users\Ayesha\AppData\Local\Temp\a85000db0433b3fd3f56e0c61fbf04.xml C:\Users\Ayesha\AppData\Local\Temp\2c1e2d8b149071d13f62c45734f660.pdf


I ran this command in the Parsr folder, but it just opened the pdf2txt.py file.
No other information came

Then I ran it with python, It ran but no console etc.

![6](https://user-images.githubusercontent.com/51691311/73546942-e1da8d80-445f-11ea-849b-ebd81e199eaf.PNG)

**Comment by AyeshaSarwar** [comment]
It shows magick identify not installed but I cannot have any information on how to download it.

**Comment by jvalls-axa** [comment]
> It shows magick identify not installed but I cannot have any information on how to download it.

https://imagemagick.org/script/download.php

**Comment by jvalls-axa** [comment]
@AyeshaSarwar I'm not windows user but I think you have to associate .py files to open with Python.

May be [this](https://gist.github.com/Hrxn/e2180e3c34bbed2c2e7e) can help you.

Reopen terminal after association is done and try again....

**Comment by AyeshaSarwar** [comment]
I did both.
All the things have been installed. 
but it still says 404 not found.

**Comment by AyeshaSarwar** [comment]
There was an error running the orchestrator: pdf2txt error:
This is the error

**Comment by jvalls-axa** [comment]
Can you paste full API console log ??

**Comment by AyeshaSarwar** [comment]
ok

**Comment by AyeshaSarwar** [comment]
[2020-01-31T16:54:43] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Api listening on port 3001!
[2020-01-31T16:55:14] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Returning the default server settings...
[2020-01-31T16:55:27] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Processing C:\Users\Ayesha\AppData\Local\Temp\cf9240ad4a6dc40a2b8a1afd2c2fbd\1b363daec9919dd025231a967158de.pdf
[2020-01-31T16:55:27] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): node ../../dist/bin/index.js --input-file C:\Users\Ayesha\AppData\Local\Temp\cf9240ad4a6dc40a2b8a1afd2c2fbd\1b363daec9919dd025231a967158de.pdf --output-folder D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\dist\output\1908-05ae1a890e0b257e438695ef05c974 --document-name 1908 --config C:\Users\Ayesha\AppData\Local\Temp\0d3c032f61c9210f94a194154d2633\7dc34d10925da122356251d2196d8b.blob
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Current version: [e1d11ac]  (HEAD -> master, origin/master, origin/HEAD) - Merge pull request #309 from 0xflotus/patch-1 - (Tue Jan 28 09:36:38 2020 +0100, GitHub <noreply@github.com>)
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Using config:
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Config {
  version: 0.5,
  cleaner: [
    'out-of-page-removal',
    [
      'whitespace-removal',
      [Object]
    ],
    [
      'redundancy-detection',
      [Object]
    ],
    [
      'table-detection',
      [Object]
    ],
    [
      'header-footer-detection',
      [Object]
    ],
    [
      'reading-order-detection',
      [Object]
    ],
    'link-detection',
    'image-detection',
    [
      'words-to-line',
      [Object]
    ],
    [
      'lines-to-paragraph',
      [Object]
    ],
    'heading-detection',
    'heading-detection-dt',
    'list-detection',
    'page-number-detection',
    'hierarchy-detection',
    [
      'regex-matcher',
      [Object]
    ]
  ],
  extractor: {
    pdf: 'pdfminer',
    img: 'tesseract',
    language: [
      'eng',
      'fra'
    ]
  },
  output: {
    granularity: 'word',
    includeMarginals: false,
    formats: {
      json: true,
      text: true,
      csv: true,
      markdown: true,
      pdf: false
    }
  }
}
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Using extractor: PdfminerExtractor
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): executing command: qpdf --decrypt --no-warn C:\Users\Ayesha\AppData\Local\Temp\cf9240ad4a6dc40a2b8a1afd2c2fbd\1b363daec9919dd025231a967158de.pdf C:\Users\Ayesha\AppData\Local\Temp\a2f1f3b5f019a4233f0c14093e497c.pdf
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): qpdf repair successfully performed on file C:\Users\Ayesha\AppData\Local\Temp\cf9240ad4a6dc40a2b8a1afd2c2fbd\1b363daec9919dd025231a967158de.pdf. New file at: C:\Users\Ayesha\AppData\Local\Temp\a2f1f3b5f019a4233f0c14093e497c.pdf
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): executing command: mutool clean C:\Users\Ayesha\AppData\Local\Temp\a2f1f3b5f019a4233f0c14093e497c.pdf C:\Users\Ayesha\AppData\Local\Temp\19e780505111da0f288143616e330d.pdf
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): mupdf cleaning successfully performed on file C:\Users\Ayesha\AppData\Local\Temp\a2f1f3b5f019a4233f0c14093e497c.pdf. Resulting file: C:\Users\Ayesha\AppData\Local\Temp\19e780505111da0f288143616e330d.pdf
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Extracting file contents with pdfminer's pdf2txt.py tool...
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): executing command: pdf2txt.py -c utf-8 -t xml -o C:\Users\Ayesha\AppData\Local\Temp\2bfd6564f31c5b0cede1635bf1a0c8.xml C:\Users\Ayesha\AppData\Local\Temp\19e780505111da0f288143616e330d.pdf
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Extracting images and fonts to C:\Users\Ayesha\AppData\Local\Temp\1c21a6dddb921e4669f2146d9ee6f5
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): executing command: mutool extract C:\Users\Ayesha\AppData\Local\Temp\19e780505111da0f288143616e330d.pdf
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1):
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): There was an error running the orchestrator: pdf2txt error:
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Exiting with code 0
[2020-01-31T16:55:28] INFO  (parsr-api/17108 on LAPTOP-HEHNCUG1): Process exited

**Comment by jvalls-axa** [comment]
Try  in new terminal window:
- `pdf2txt.py -c utf-8 PATH_TO_PDF`. Does itt display all PDF contents?
- 'python --version' what version do you have?

**Comment by AyeshaSarwar** [comment]
3.7
![rtgf](https://user-images.githubusercontent.com/51691311/73559577-20c80d80-4477-11ea-9574-f3d8489bdd7b.PNG)
It pops up the pdf2txt.py file

**Comment by jvalls-axa** [comment]
Because the .py association is not properly done..... Right now notePad is the one associated to .py files.

- Type `where python`' --> it should return your python installation folder.
- Then try again this `assoc .py=PythonScript` & `ftype PythonScript=YOUR_PYTHON_FOLDER "%1" %*`
- Close console app, open it & try again

**Comment by AyeshaSarwar** [comment]
Still same
It pops up pdf2txt.py file

**Comment by AyeshaSarwar** [comment]
![1](https://user-images.githubusercontent.com/51691311/73561825-92a25600-447b-11ea-98a5-86a3f2d408c7.PNG)
Also, I have pdf2txt.py file in Anaconda3 and python3 separately.

**Comment by AyeshaSarwar** [comment]
![Capture](https://user-images.githubusercontent.com/51691311/73562683-70113c80-447d-11ea-9438-ad33199ae641.PNG)
Also if i run this with python command it says this

**Comment by jvalls-axa** [comment]
Maybe we missed double quotes in association command ??

Like [this](https://i.stack.imgur.com/D2hdU.png)

Any way I will try to test Parsr under Windows next Monday!

**Comment by AyeshaSarwar** [comment]
I tried but same

Error: File not found
    at FileManager.checkFile (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\dist\FileManager.js:88:19)
    at FileManager.getFilePath (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\dist\FileManager.js:52:25)
    at ApiServer.handleGetFile (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\dist\api.js:359:41)
    at ApiServer.handleGetJson (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\dist\api.js:314:14)
    at Layer.handle [as handle_request] (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\node_modules\express\lib\router\layer.js:95:5)
    at next (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\node_modules\express\lib\router\layer.js:95:5)
    at D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\node_modules\express\lib\router\index.js:281:22
    at param (D:\EducAtiOn\Thesis\Tasks\2\Parsr\api\server\node_modules\express\lib\router\index.js:354:14)

**Comment by AyeshaSarwar** [comment]
If I run this command 
python pdf2txt.py samples/simple1.pdf
from this location where pdf2txt.py exists
C:\Users\Ayesha\AppData\Local\Programs\Python\Python37\Scripts
It executes

**Comment by jvalls-axa** [comment]
can you contact me by email ?? see my profile

**Comment by AyeshaSarwar** [comment]
ok

**Comment by AyeshaSarwar** [comment]
I chose the default program to open py files with python.exe(can be found where python is installed)
or write
where python 
on cmd to know its location

and hence the pdf2txt.py command runs on cmd

**Comment by jvalls-axa** [comment]
Fixed by #321
