### ISSUE TITLE
Orchestrator TypeError

### ISSUE THREAD

**Issue by sjaintdl** [axa-group/Parsr#367]
There was an error running the orchestrator: TypeError: Cannot read property '1' of null
 at Object.extractPageNodeIds (D:\Jain University\Final Year\Parsr\Parsr-master\dist\src\processing\ImageDetectionModule\DumpPdfParsr.js:33:91)
    at ImageDetectionModule.<anonymous> (D:\Jain University\Final Year\Parsr\Parsr-master\dist\src\processing\ImageDetectionModule\ImageDetectionModule.js:202:49)
    at step (D:\Jain University\Final Year\Parsr\Parsr-master\dist\src\processing\ImageDetectionModule\ImageDetectionModule.js:61:23)
    at Object.next (D:\Jain University\Final Year\Parsr\Parsr-master\dist\src\processing\ImageDetectionModule\ImageDetectionModule.js:42:53)
    at fulfilled (D:\Jain University\Final Year\Parsr\Parsr-master\dist\src\processing\ImageDetectionModule\ImageDetectionModule.js:33:58)

I am getting this error after uploading the PDF.

**Comment by jvalls-axa** [comment]
Hi @sjaintdl 

Could you please attach the document you're using?

Thanks

**Comment by sjaintdl** [comment]
> Hi @sjaintdl
> 
> Could you please attach the document you're using?
> 
> Thanks


Hi @jvalls-axa,
Please find the attachments.
[sample-invoice.pdf](https://github.com/axa-group/Parsr/files/4374835/sample-invoice.pdf)

[airasia-q1.pdf](https://github.com/axa-group/Parsr/files/4374830/airasia-q1.pdf)

**Comment by jvalls-axa** [comment]
Hi @sjaintdl 

Could you please try again with last [release](https://github.com/axa-group/Parsr/releases/tag/v0.11.1) ?

**Comment by sjaintdl** [comment]
Thanks @jvalls-axa 

After making changes in code that you sent and also In last release version OCR is working good without any changes in code.

But other issue is coming as mentioned below-

It is completely processing some documents but with some documents it is giving error when processing with pdfminer -

There was an error running the orchestrator: TypeError: Cannot read property 'map' of undefined
    at thereAreFakeSpaces (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:390:10)
    at breakLineIntoWords (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:307:22)
    at D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:211:47
    at Array.forEach (<anonymous>)
    at getPage (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:206:24)
    at D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:185:78
    at Array.forEach (<anonymous>)
    at getPages (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:185:28)
    at jsParser (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:177:53)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by jvalls-axa** [comment]
Hi @sjaintdl 

Could you please attach document that raises the issue ??

**Comment by sjaintdl** [comment]
Hi @jvalls-axa ,

You can check it with this attachment - 
[Shashank_L.pdf](https://github.com/axa-group/Parsr/files/4386132/Shashank_L.pdf)

**Comment by sjaintdl** [comment]
> Hi @sjaintdl
> 
> Could you please attach document that raises the issue ??
