### ISSUE TITLE
Orchestrator Error

### ISSUE THREAD

**Issue by sjaintdl** [axa-group/Parsr#372]
Hello @jvalls-axa ,

By mistake i have closed the request so i raised a new request for the same you can find the attachment below for this error - 
 
It is completely processing some documents but with some documents it is giving error when processing with pdfminer -

There was an error running the orchestrator: TypeError: Cannot read property 'map' of undefined
at thereAreFakeSpaces (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:390:10)
at breakLineIntoWords (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:307:22)
at D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:211:47
at Array.forEach ()
at getPage (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:206:24)
at D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:185:78
at Array.forEach ()
at getPages (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:185:28)
at jsParser (D:\Jain University\Final Year\Parsr\Parsr-0.11.1\Parsr-0.11.1\dist\src\input\pdfminer\pdfminer.js:177:53)
at processTicksAndRejections (internal/process/task_queues.js:97:5)

[DemoInvoice.pdf](https://github.com/axa-group/Parsr/files/4386237/DemoInvoice.pdf)

**Comment by jvalls-axa** [comment]
Hi @sjaintdl 

Fixed in [0.11.2](https://github.com/axa-group/Parsr/releases/tag/v0.11.2)

**Comment by sjaintdl** [comment]
Thanks @jvalls-axa ,

Now it is working well after installing your latest version.
