### ISSUE TITLE
Cleanerjs crash on docker image v.1.2.2

### ISSUE THREAD

**Issue by jalberto** [axa-group/Parsr#512]
**Summary**
Send a PDF using default config crash module Cleaner.js

**Steps To Reproduce**

1. Send multipage PDF using curl
2. Check logs
3. See error

```
[2021-01-22T11:06:41] ERROR (parsr-api/6 on parsr-bb9d57c85-bxwmb): /opt/app-root/src/dist/src/Cleaner.js:201
            throw new Error("Module " + moduleClass.moduleName + " has unresolved dependencies (" + unresolvedStr + ").");
            ^

Error: Module lines-to-paragraph has unresolved dependencies (words-to-line-new).
    at Cleaner.checkDependenciesAndAdd (/opt/app-root/src/dist/src/Cleaner.js:201:19)
    at /opt/app-root/src/dist/src/Cleaner.js:136:19
    at Array.forEach (<anonymous>)
    at Cleaner.parseLatestConfig (/opt/app-root/src/dist/src/Cleaner.js:123:16)
    at new Cleaner (/opt/app-root/src/dist/src/Cleaner.js:88:18)
    at main (/opt/app-root/src/dist/bin/index.js:72:19)
    at Object.<anonymous> (/opt/app-root/src/dist/bin/index.js:204:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

[2021-01-22T11:06:41] INFO  (parsr-api/6 on parsr-bb9d57c85-bxwmb): Process exited
```

**Expected behavior**
no crashes

**Environment**

- Reference commit/version: v1.2.2
- Other platform details: docker

**Comment by jalberto** [comment]
This happens because some old config was cached, I wonder if when some module is not configured it should always have a fallback instead of crash
