### ISSUE TITLE
An error on table export to CSV format

### ISSUE THREAD

**Issue by aarohijohal** [axa-group/Parsr#57]
**Summary**
The table export procedure fails for a particular table.
There seems to be an error somewhere in the pipeline where the table is conveted to an array.

**Steps To Reproduce**
1. Make sure table-detection is turned on.
2. Pass the attached file through the pipeline.
3. Observe a TypeError in `Table.ts`.

**Expected behavior**
A seemless export of the table to CSV.

**Actual behavior**
The following error is returned:
```
[2019-09-09T04:43:06] ERROR (parsr): Cannot set property '0' of undefined
    TypeError: Cannot set property '0' of undefined
        at Table.toArray (/Users/me/Code/parsr/dist/src/types/DocumentRepresentation/Table.js:337:47)
        at /Users/me/Code/parsr/dist/src/exporters/MarkdownExporter.js:89:47
        at Array.forEach (<anonymous>)
        at /Users/me/Code/parsr/dist/src/exporters/MarkdownExporter.js:50:27
        at Array.forEach (<anonymous>)
        at MarkdownExporter.getMarkdown (/Users/me/Code/parsr/dist/src/exporters/MarkdownExporter.js:49:24)
        at MarkdownExporter.export (/Users/me/Code/parsr/dist/src/exporters/MarkdownExporter.js:44:48)
        at /Users/me/Code/parsr/dist/bin/index.js:130:107
        at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Environment**
 - Reference commit/version: 16a4e23e03f5e9a9d4de98ad52c73c311d1cbb57
 - Other platform details: npm 6.9.0
 - OS: MacOS 10.14.5

**Attached file***
[t2 (dragged).pdf](https://github.com/axa-group/Parsr/files/3588699/t2.dragged.pdf)

**Comment by aarohijohal** [comment]
Commit 730e33784e7119eee4a3127a41502eb871338ff1 resolves this
