### ISSUE TITLE
weakref module error

### ISSUE THREAD

**Issue by NilesRath** [axa-group/Parsr#581]
$ pwd
/opt/app-root/src/demo/parsr-jupyter-demo
$ pipenv install
Traceback (most recent call last):
  File "/opt/app-root/src/.local/bin/pipenv", line 6, in <module>
    from pipenv import cli
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/pipenv/__init__.py", line 22, in <module>
    from pipenv.vendor.vistir.compat import ResourceWarning, fs_str
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/__init__.py", line 4, in <module>
    from .compat import (
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/compat.py", line 13, in <module>
    from .backports.tempfile import NamedTemporaryFile as _NamedTemporaryFile
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/__init__.py", line 6, in <module>
    from .tempfile import NamedTemporaryFile
  File "/opt/app-root/src/.local/lib/python2.7/site-packages/pipenv/vendor/vistir/backports/tempfile.py", line 15, in <module>
    from backports.weakref import finalize
ImportError: No module named weakref

**Comment by BinaryBrain** [comment]
Please use Python 3.
