### ISSUE TITLE
buildozer android debug error

### ISSUE THREAD

**Issue by hussam132** [axa-group/Parsr#80]
i get the following error when i run "buildozer android debug"
kivy@kivy-VirtualBox:/media/sf_hussam$     buildozer android debug
```sh
# Check configuration tokens
# Ensure build layout
# Check configuration tokens
# Read available permissions from api-versions.xml
# Preparing build
# Check requirements for android
# Run 'dpkg --version'
# Cwd None
Debian `dpkg' package management program version 1.17.5 (amd64).
This is free software; see the GNU General Public License version 2 or
later for copying conditions. There is NO warranty.
# Search for Git (git)
#  -> found at /usr/bin/git
# Search for Cython (cython)
#  -> found at /usr/local/bin/cython
# Search for Java compiler (javac)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/bin/javac
# Search for Java keytool (keytool)
#  -> found at /usr/lib/jvm/java-7-openjdk-amd64/jre/bin/keytool
# Install platform
# Run '/usr/bin/python -m pip install -q --user \'appdirs\' \'colorama>=0.3.3\' \'jinja2\' \'six\' \'enum34; python_version<"3.4"\' \'sh>=1.10; sys_platform!="nt"\' \'pep517\' \'pytoml\' \'virtualenv\''
# Cwd None
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1435, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 671, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 901, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 139, in move_wheel_files
    scheme = distutils_scheme(name, user=user, home=home, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 155, in distutils_scheme
    i.finalize_options()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "/usr/lib/python2.7/distutils/command/install.py", line 357, in finalize_options
    self.create_home_path()
  File "/usr/lib/python2.7/distutils/command/install.py", line 593, in create_home_path
    os.makedirs(path, 0700)
  File "/usr/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/kivy/.local/lib/python2.7'

Storing debug log for failure in /tmp/tmptHQY8s
# Command failed: /usr/bin/python -m pip install -q --user 'appdirs' 'colorama>=0.3.3' 'jinja2' 'six' 'enum34; python_version<"3.4"' 'sh>=1.10; sys_platform!="nt"' 'pep517' 'pytoml' 'virtualenv'
# 
# Buildozer failed to execute the last command
# The error might be hidden in the log above this error
# Please read the full log, and search for it before
# raising an issue with buildozer itself.
# In case of a bug report, please add a full log with log_level = 2
```
please help

GitHub is my last chance I search about this issue in internet many times 
and no solution !!

**Comment by hussam132** [comment]
I'm using buildozer on virtualbox

**Comment by BinaryBrain** [comment]
Are you sure it is related to Parsr?  
Anyway, you have a permission issue.

**Comment by cipri-tom** [comment]
Yeah, just check that you have write permission on `/home/kivy/.local/lib/python2.7` because it is trying to run `pip install` and that is its default path.

**Comment by hussam132** [comment]
that's true but how i can do that
i can open the this path in the terminal

**Comment by hussam132** [comment]
I'm new in ubuntu and i don't knew how to change the  permission

**Comment by BinaryBrain** [comment]
You should have a look here: https://tutorials.ubuntu.com (and on Google).
